/*
 * SpiderBrain v3 © 2026 Perform Digital Pvt Ltd
 *
 * Licensed under BUSL-1.1. Free for personal, educational, research, and open-source use. Forking and internal modification for research are permitted. Redistribution, hosted usage, commercial deployment, resale, sublicensing, or distribution of derivative works require a separate commercial license from Perform Digital Pvt Ltd.
 *
 * Contact: contact@perform.digital
 */

// render.mjs - regenerate the human-readable markdown VIEWS from the graph.
//
// Every file here carries a GENERATED banner and is disposable. The webmap is
// now a COLUMN: one theta master at the head, then its gamma legs - 1 + 8 = 9.

const fmtDate = (isoStr) => {
  if (!isoStr) return '-';
  const d = new Date(isoStr);
  return Number.isNaN(d.getTime())
    ? '-' : d.toISOString().slice(0, 16).replace('T', ' ');
};
const score = (n) => (typeof n === 'number' ? n.toFixed(1) : '-');
const cell = (s) => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\n+/g, ' ');
const lyr = (n) => (n.isMaster ? 'θ' : 'γ');

export function banner(graph, title) {
  return (
    `<!-- GENERATED by spiderbrain - DO NOT EDIT.\n` +
    `     source: synganglion.json  hash:${(graph && graph.sourceHash) || '?'}  ` +
    `built:${(graph && graph.generatedAt) || '?'}\n` +
    `     Edit the curated source (config / overrides / changelog), then rebuild. -->\n` +
    `# ${title}\n`
  );
}

const sortedNodeEntries = (graph, key) =>
  Object.entries(graph.nodes).sort((a, b) => {
    if (key === 'recency') {
      const ta = a[1].lastChangedAt || '';
      const tb = b[1].lastChangedAt || '';
      return tb.localeCompare(ta) || (b[1].webscore - a[1].webscore);
    }
    return (b[1].webscore - a[1].webscore) || a[0].localeCompare(b[0]);
  });

/** spideyorder - every node ranked by webscore, with its live amplitude. */
export function renderSpideyorder(graph) {
  let out = banner(graph, 'spideyorder - the supraesophageal map');
  out += `\nEvery node ranked by **webscore** (mass - static blast potential). ` +
    `**amp** is the live amplitude (mass scaled by how recently the master ` +
    `fired); **L** is the layer - θ master, γ executor.\n\n`;
  out += `**Prey:** ${graph.prey || '-'}\n\n`;
  out += `| # | webscore | amp | L | rhythm | ring | node | role |\n`;
  out += `|--:|--:|--:|:-:|--:|--:|---|---|\n`;
  let i = 0;
  for (const [id, n] of sortedNodeEntries(graph, 'order')) {
    i += 1;
    out += `| ${i} | **${score(n.webscore)}** | ${score(n.amplitude)} | ${lyr(n)} | ` +
      `${n.rhythm || 0} | ${n.ring} | \`${cell(id)}\` | ${cell(n.role)} |\n`;
  }
  return out + `\n_${i} nodes · ${graph.stats.masterCount} masters · ` +
    `${graph.stats.columnCount} columns · ${graph.stats.edgeCount} synapses._\n`;
}

/** spideymove - every node ranked by recency (git commit time). */
export function renderSpideymove(graph) {
  let out = banner(graph, 'spideymove - the subesophageal map');
  out += `\nEvery node ranked by **recency** - the last git commit that touched ` +
    `it. The top of this list is what is hot right now.\n\n`;
  out += `| # | last changed | L | node | cluster | webscore | stale deps |\n`;
  out += `|--:|---|:-:|---|---|--:|--:|\n`;
  let i = 0;
  for (const [id, n] of sortedNodeEntries(graph, 'recency')) {
    i += 1;
    const stale = (n.dependencyChangedAt || []).length;
    out += `| ${i} | ${fmtDate(n.lastChangedAt)} | ${lyr(n)} | \`${cell(id)}\` | ` +
      `${cell(n.cluster)} | ${score(n.webscore)} | ${stale || ''} |\n`;
  }
  return out + `\n_"stale deps" = a dependency changed after this node did._\n`;
}

/** webmap - one cluster as a COLUMN: a theta master at the head, gamma legs below. */
export function renderWebmap(graph, clusterName, changelogExcerpt) {
  const c = graph.clusters[clusterName];
  const K = graph.displayK || 8;
  let out = banner(graph, `${clusterName} - webmap`);
  if (!c) return out + `\n_No nodes in cluster \`${clusterName}\`._\n`;

  out += `\n**Cluster webscore ${score(c.webscore)}** · ${c.nodeCount} nodes · ` +
    `_${cell(c.title)}_\n\n`;

  const masterId = c.master;
  const m = masterId && graph.nodes[masterId];
  const legs = c.topNodes.filter((id) => id !== masterId).slice(0, K);

  out += `## The column - 1 master + ${legs.length} legs\n\n`;
  out += `> Theta sets the rhythm; gamma executes. A fault may fall down this ` +
    `column; a fault that climbs from a leg into the master is a **hard stop**.\n\n`;
  out += `| | webscore | amp | rhythm | node | role |\n|---|--:|--:|--:|---|---|\n`;
  if (m) {
    out += `| **θ master** | **${score(m.webscore)}** | ${score(m.amplitude)} | ` +
      `${m.rhythm || 0} | \`${cell(masterId)}\` | ${cell(m.role)} |\n`;
  }
  for (const id of legs) {
    const n = graph.nodes[id];
    if (!n) continue;
    const off = n.master && n.master !== masterId
      ? ` ⟂ modulated by \`${cell(n.master)}\`` : '';
    out += `| γ leg | ${score(n.webscore)} | ${score(n.amplitude)} | ` +
      `${n.rhythm || 0} | \`${cell(id)}\` | ${cell(n.role)}${off} |\n`;
  }

  // external legs - cross-cluster dependencies
  const inCluster = new Set(
    Object.keys(graph.nodes).filter((id) => graph.nodes[id].cluster === clusterName),
  );
  const external = new Map();
  for (const id of inCluster) {
    for (const dep of graph.nodes[id].dependsOn || []) {
      if (!inCluster.has(dep) && graph.nodes[dep]) external.set(dep, graph.nodes[dep]);
    }
  }
  const extTop = [...external.entries()]
    .sort((a, b) => b[1].webscore - a[1].webscore).slice(0, K);
  out += `\n## External legs - what this feature leans on outside itself\n\n`;
  if (!extTop.length) {
    out += `_Nothing - this cluster is self-contained._\n`;
  } else {
    out += `| webscore | L | node | cluster | role |\n|--:|:-:|---|---|---|\n`;
    for (const [id, n] of extTop) {
      out += `| ${score(n.webscore)} | ${lyr(n)} | \`${cell(id)}\` | ` +
        `${cell(n.cluster)} | ${cell(n.role)} |\n`;
    }
  }

  out += `\n## Synapses - what each leg is wired to\n\n`;
  for (const id of [masterId, ...legs].filter(Boolean)) {
    const n = graph.nodes[id];
    if (!n) continue;
    out += `### \`${cell(id)}\` · ${lyr(n)} · webscore ${score(n.webscore)} · cell ${n.cell}\n`;
    const dOn = (n.dependsOn || []).slice(0, K);
    const dBy = (n.dependedOnBy || []).slice(0, K);
    out += `- **depends on** (${(n.dependsOn || []).length}): ` +
      (dOn.length ? dOn.map((d) => `\`${cell(d)}\``).join(', ') : '_nothing_') + `\n`;
    out += `- **depended on by** (${(n.dependedOnBy || []).length}): ` +
      (dBy.length ? dBy.map((d) => `\`${cell(d)}\``).join(', ') : '_a leaf_') + `\n`;
    if ((n.modulatedBy || []).length) {
      out += `- **modulated by** (θ): ` +
        n.modulatedBy.map((d) => `\`${cell(d)}\``).join(', ') + `\n`;
    }
    const stale = n.dependencyChangedAt || [];
    if (stale.length) {
      out += `- ⚠ **fired synapses**: ` +
        stale.map((s) => `\`${cell(s.dep)}\` (${fmtDate(s.at)})`).join(', ') + `\n`;
    }
  }

  out += `\n## Changelog\n\nCurated history: [\`changelog.md\`](./changelog.md). ` +
    `Latest entries:\n\n`;
  out += (changelogExcerpt && changelogExcerpt.trim())
    ? changelogExcerpt.trim() + '\n' : '_No entries yet._\n';
  return out;
}

/** molt-report - the read-only drift audit. */
export function renderMolt(graph, report) {
  let out = banner(graph, `molt report - ${((graph && graph.generatedAt) || '').slice(0, 10)}`);
  const ok = report.orphans.length + report.unindexed.length
    + report.dangling.length === 0;
  out += `\n**${ok ? '✅ Clean molt - the brain matches reality.'
    : '⚠ The brain has drifted from reality. Review below.'}**\n\n`;
  out += `| integrity check | count |\n|---|--:|\n`;
  out += `| orphan nodes (file gone) | ${report.orphans.length} |\n`;
  out += `| unindexed files (no node) | ${report.unindexed.length} |\n`;
  out += `| dangling edges (target deleted) | ${report.dangling.length} |\n`;
  out += `\n_Informational: ${report.modified.length} file(s) changed since the ` +
    `last build, ${report.renames.length} probable rename(s), ` +
    `${report.divergence.length} webscore divergence(s)._\n`;

  const section = (title, items, fmt) => {
    out += `\n## ${title}\n\n`;
    if (!items.length) { out += `_None._\n`; return; }
    for (const it of items) out += `- ${fmt(it)}\n`;
  };
  section('Orphan nodes - indexed, but the file is gone', report.orphans,
    (o) => `\`${cell(o.id)}\` - used to hold up ${o.blast} node(s)`);
  section('Probable renames', report.renames,
    (r) => `\`${cell(r.from)}\` → \`${cell(r.to)}\` - migrate its override key`);
  section('Unindexed files - on disk, but not in the brain', report.unindexed,
    (id) => `\`${cell(id)}\` - rebuild to index it`);
  section('Dangling edges', report.dangling,
    (e) => `\`${cell(e[0])}\` → \`${cell(e[1])}\``);
  section('Modified since the last build (informational)', report.modified,
    (m) => `\`${cell(m.id)}\` - content hash changed; rebuild to refresh`);
  section('Webscore divergence (informational)', report.divergence,
    (d) => `\`${cell(d.id)}\` - override ${score(d.webscore)} vs auto ` +
      `${score(d.webscoreAuto)} (Δ ${score(d.delta)})`);
  return out;
}

/** cascade-report - the nerve net's reading of an injected or detected fault. */
export function renderCascade(graph, report) {
  const s = report.signature;
  let out = banner(graph, `cascade report - ${report.origins.join(', ')}`);

  if (report.hardStop && report.hardStop.tripped) {
    out += `\n## ⛔ HARD STOP\n\n`;
    out += `A cluster (gamma) fault climbed into a theta **master**. Gamma may ` +
      `never fell theta - the column has lost its frame. Masters reached:\n\n`;
    for (const mh of report.hardStop.masters) {
      out += `- \`${cell(mh.id)}\` (cell ${mh.cell}, depth +${mh.depth})\n`;
    }
    out += `\nThe cascade was halted at each master - it did not propagate ` +
      `through. Fix the master, not the legs.\n`;
  }

  out += `\n**Injected:** ${report.badIds.length} node(s). ` +
    `**Topological origin(s):** ${report.origins.length}.\n\n`;
  for (const oc of s.originCells || []) {
    out += `- \`${cell(oc.id)}\` → cell **${oc.cell}** ` +
      `(ring ${oc.ring}, sector ${oc.sector})\n`;
  }
  out += `\n| signature | value |\n|---|--:|\n`;
  out += `| breadth (nodes hit) | ${s.breadth} |\n`;
  out += `| depth (shells) | ${s.depth} |\n`;
  out += `| speed (nodes / shell) | ${s.speed} |\n`;
  out += `| immediate fan-out | ${s.immediateFanout} |\n`;
  out += `| cells tripped | ${s.cellsTripped} |\n`;
  out += `| rings crossed | ${s.ringsCrossed} |\n`;
  out += `| sectors crossed | ${s.sectorsCrossed} |\n`;
  out += `| weighted severity (Σ webscore) | ${s.weightedSeverity} |\n`;
  out += `| hard stop | ${s.hardStop ? 'YES' : 'no'} |\n`;

  out += `\n## Wavefront - the shockwave, shell by shell\n\n`;
  report.wavefront.forEach((n, d) => {
    out += `- depth ${d}: ${n} node(s) ${'█'.repeat(Math.min(40, n))}\n`;
  });

  out += `\n## Cells tripped - in order (first cell = the origin)\n\n`;
  out += `| trip depth | cell | ring | sector | nodes |\n|--:|---|--:|---|--:|\n`;
  for (const c of report.cells) {
    out += `| ${c.tripDepth} | ${c.cell} | ${c.ring} | ${c.sector} | ${c.nodeCount} |\n`;
  }

  out += `\n## Blast radius - nodes hit (top 25 by webscore)\n\n`;
  out += `| depth | webscore | L | node | cell |\n|--:|--:|:-:|---|---|\n`;
  for (const b of report.blast.slice(0, 25)) {
    out += `| ${b.depth} | ${score(b.webscore)} | ${b.isMaster ? 'θ' : 'γ'} | ` +
      `\`${cell(b.id)}\` | ${b.cell} |\n`;
  }
  if (report.blast.length > 25) out += `\n_…and ${report.blast.length - 25} more._\n`;
  return out;
}
